# Generated by Django 3.0.8 on 2020-08-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_imagenesproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenesproducto',
            name='imagen',
            field=models.ImageField(upload_to='imagenes_producto'),
        ),
    ]
